<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>$(SolutionDir)ThirdParty\SDL3\include;$(SolutionDir)ThirdParty\imgui;$(SolutionDir)ThirdParty\imgui\backends;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <AdditionalOptions>/utf-8 %(AdditionalOptions)</AdditionalOptions>
    </ClCompile>
    <Link>
      <AdditionalLibraryDirectories>$(SolutionDir)ThirdParty\SDL3\VisualC\$(Platform)\$(Configuration);%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
      <AdditionalDependencies>SDL3.lib;%(AdditionalDependencies)</AdditionalDependencies>
    </Link>
    <PostBuildEvent>
      <Command>if exist "$(SolutionDir)ThirdParty\SDL3\VisualC\$(Platform)\$(Configuration)\SDL3.dll" copy /Y "$(SolutionDir)ThirdParty\SDL3\VisualC\$(Platform)\$(Configuration)\SDL3.dll" "$(OutDir)"
if exist "$(SolutionDir)Assets" xcopy /E /I /Y "$(SolutionDir)Assets" "$(OutDir)Assets"
if exist "$(ProjectDir)Shaders" xcopy /E /I /Y "$(ProjectDir)Shaders" "$(OutDir)Shaders"</Command>
    </PostBuildEvent>
  </ItemDefinitionGroup>
</Project>
